version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: satellite_sever
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: satellite_sever
    ports:
      - "1208:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: